server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qp-assessment
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

secret_key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
